config_version: '1.0'
config_name: base
config_steps:
    - data:
        dataset_version: # NAME OF DATASET VERSION
    - transform:
    - model:
    - sample:
        number_of_rows: ''
    - metrics: